# Generated by Django 5.1.3 on 2025-01-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='craeted_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
